Repository WordPress/twentynineteen, pull requests merged in 2018-10, with the labels that each got.

#57 Update text colors to pass WCAG AA
  sass/variables-site/_colors.scss
  style-editor.css
  style.css
Labels: accessibility

#132 Remove unnecessary display property from .alignleft and .alignright
  sass/modules/_alignments.scss
  style.css
Labels: code quality

#167 Fix linting errors causing the Travis build to fail
  .editorconfig
  archive.php
  classes/class-twentynineteen-svg-icons.php
  classes/class-twentynineteen-walker-comment.php
  comments.php
  footer.php
  functions.php
  header.php
  inc/customizer.php
  inc/icon-functions.php
  inc/jetpack.php
  inc/template-functions.php
  inc/template-tags.php
  inc/ui-icons.php
  js/customizer.js
  page.php
  single.php
  template-parts/content/content-page.php
  template-parts/content/content-single.php
  template-parts/content/content.php
  template-parts/header/entry-header.php
  template-parts/header/site-branding.php
  template-parts/post/author-info.php
  template-parts/post/discussion-meta.php
Labels: code quality

#188 Cleared TODO comments across all files - task #171
  classes/class-twentynineteen-svg-icons.php
  classes/class-twentynineteen-walker-comment.php
  footer.php
  inc/icon-functions.php
  inc/template-functions.php
  inc/template-tags.php
  inc/ui-icons.php
  js/customizer.js
  template-parts/header/entry-header.php
  template-parts/header/site-branding.php
  template-parts/post/author-info.php
  template-parts/post/discussion-meta.php
Labels: code quality

#141 Scale down our largest two font sizes on mobile.
  sass/blocks/_blocks.scss
  sass/typography/_headings.scss
  style-editor.css
  style-editor.scss
  style.css
Labels: enhancement

#203 Only show site-title as a h1 when it's the homepage/frontpage
  sass/typography/_headings.scss
  style.css
  template-parts/header/site-branding.php
Labels: accessibility, enhancement

#227 Fix left/right aligned pullquote block spacing on smaller screens.
  sass/blocks/_blocks.scss
  sass/typography/_copy.scss
  sass/typography/_headings.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#242 Fix linting errors
  inc/template-functions.php
Labels: code quality

#249 Remove unused IE stylesheet enqueue.
  functions.php
Labels: bug

#272 Add focusable: false attribute to SVGs
  classes/class-twentynineteen-svg-icons.php
Labels: accessibility, bug

#290 Fix the alignment for the double arrow
  classes/class-twentynineteen-svg-icons.php
Labels: code quality

#362 Update classic editor blockquote styles
  sass/elements/_elements.scss
  sass/typography/_copy.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#327 Customizer: introduce theme option to disable the image filter
  inc/customizer.php
  inc/template-functions.php
  js/customizer.js
  sass/site/header/_site-featured-image.scss
  style-rtl.css
  style.css
Labels: has patch

#368 Fix attachment-page problems
  image.php
  single.php
  template-parts/content/content-single.php
Labels: has patch

#389 Adjust alignfull margins to match the editor.
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: enhancement

#399 Add aligncenter rules for the cover image block
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug

#410 👍 Add text-domain
  inc/customizer.php
Labels: code quality

#414 Set aligncenter rules for the audio block
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug

#424 Fix submenu on mobile and desktop
  sass/navigation/_menu-main-navigation.scss
  style.css
Labels: bug

#425 Fix RTL alignments
  sass/modules/_alignments.scss
  style-rtl.css
  style.css
Labels: bug

#418 417 - Run JSHint in Travis only once
  .travis.yml
Labels: has patch
