Repository WordPress/twentynineteen, pull requests merged in 2018-11, with the labels that each got.

#262 Consolidate editor styles
  functions.php
  package.json
  style-editor-customizer.css
  style-editor-customizer.scss
  style-editor-frame.css
  style-editor-frame.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
Labels: code quality, enhancement, in progress

#456 Update cover image text alignment
  style-editor.css
  style-editor.scss
Labels: bug

#455 Fix alignment of dot separator in the editor
  style-editor.css
  style-editor.scss
Labels: bug

#454 Fix the width of nested blocks
  style-editor.css
  style-editor.scss
Labels: bug

#465 Decrease font size for widgets and widget-based blocks.
  sass/blocks/_blocks.scss
  sass/site/secondary/_widgets.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: enhancement

#462 Add space to entry header on small screens
  sass/site/header/_site-featured-image.scss
  sass/site/header/_site-header.scss
  style-rtl.css
  style.css
Labels: enhancement

#450 responsive featured image
  functions.php
  header.php
  inc/template-tags.php
  sass/site/header/_site-featured-image.scss
  style-rtl.css
  style.css
Labels: enhancement

#472 Add an icon for last.fm
  CONTRIBUTORS.md
  classes/class-twentynineteen-svg-icons.php
Labels: enhancement

#473 Fix handle used for exporting twentynineteenScreenReaderText variable
  functions.php
Labels: bug, question

#490 Adds smarter math to the gallery widget
  sass/media/_galleries.scss
  style-rtl.css
  style.css
Labels: needs testing

#392 Adds :focus-within polyfill to the Sass build tool
  inc/back-compat.php
  package-lock.json
  package.json
  postcss.config.js
  style-editor.css
  style-rtl.css
  style.css
Labels: needs testing

#495 Minor: Move site logo closer to the title/menu.
  sass/site/header/_site-header.scss
  style-rtl.css
  style.css
Labels: enhancement

#498 Fix headihng block editor styles for bold text
  style-editor.css
  style-editor.scss
Labels: has patch

#497 Fix editor style for bold text in Cover Image block
  style-editor.css
  style-editor.scss
Labels: has patch

#486 Add additional rtl:ignore rules
  sass/blocks/_blocks.scss
  sass/modules/_alignments.scss
  style-rtl.css
  style.css
Labels: bug, needs testing

#502 Update front end margins to match the editor on desktop screens
  inc/color-patterns.php
  sass/blocks/_blocks.scss
  sass/media/_captions.scss
  sass/mixins/_mixins-master.scss
  sass/navigation/_next-previous.scss
  sass/site/footer/_site-footer.scss
  sass/site/header/_site-featured-image.scss
  sass/site/header/_site-header.scss
  sass/site/primary/_archives.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
  sass/variables-site/_structure.scss
  style-rtl.css
  style.css
Labels: enhancement

#516 Fix margins + certain instances of alignfull blocks on small screens
  sass/blocks/_blocks.scss
  sass/mixins/_utilities.scss
  sass/variables-site/_structure.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#520 Update post title font weight in the editor
  style-editor.css
  style-editor.scss
Labels: bug

#453 Add information about testing and submitting fixes to contributing.md
  CONTRIBUTING.md
Labels: task

#444 443 - Fix PHP syntax errors not failing Travis build
  .travis.yml
Labels: code quality, needs testing

#522 Fixes margins on archive and search page-headers
  sass/site/primary/_archives.scss
  style-rtl.css
  style.css
Labels: bug

#532 no color CSS in header when default used
  functions.php
Labels: bug, has patch

#463 Add a font family overwrite for nonbreaking spaces
  fonts/NonBreakingSpaceOverride.woff
  fonts/NonBreakingSpaceOverride.woff2
  style-editor.css
  style-editor.scss
Labels: bug, has patch

#533 Fix comment area margins
  sass/site/primary/_comments.scss
  style-rtl.css
  style.css
Labels: bug

#526 Fix additional issues with columns block.
  style-editor.css
  style-editor.scss
Labels: bug, has patch

#521 [In Progress] Improve Gutenberg fallback styles
  sass/blocks/_blocks.scss
  sass/elements/_tables.scss
  sass/site/secondary/_widgets.scss
  style-rtl.css
  style.css
Labels: bug, has patch

#508 🐛 FIX: Indentation Consistency with Tabs
  js/touch-navigation.js
Labels: code quality

#509 🐛 FIX: inline documentation
  functions.php
Labels: code quality

#372 356: CSS selectors as per coding standards
  sass/blocks/_blocks.scss
  sass/elements/_elements.scss
  sass/elements/_tables.scss
  sass/navigation/_next-previous.scss
  sass/site/header/_site-featured-image.scss
  sass/site/primary/_posts-and-pages.scss
  sass/typography/_copy.scss
  sass/typography/_headings.scss
  style-rtl.css
  style.css
Labels: code quality

#534 On small screens, move left/right margins to parent wrappers instead, minor comments area fixes.
  inc/color-patterns.php
  sass/blocks/_blocks.scss
  sass/navigation/_next-previous.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
  style-rtl.css
  style.css
Labels: bug

#544 Unset nested content selector styles for easier shortcode and plugin compatibility
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug, has patch, needs testing

#543 Add custom colors support for text selection CSS
  inc/color-patterns.php
  sass/elements/_elements.scss
  style-rtl.css
  style.css
Labels: bug, has patch

#551 Add .entry wrapper class to custom color button styles
  inc/color-patterns.php
Labels: bug

#552 Update Pullquote Block styles for better front/back end consistency
  sass/blocks/_blocks.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#485 Refactor menu UI for better consistency across interaction types
  classes/class-twentynineteen-svg-icons.php
  functions.php
  inc/color-patterns.php
  inc/template-functions.php
  js/priority-menu.js
  js/touch-keyboard-navigation.js
  js/touch-navigation.js
  sass/navigation/_menu-main-navigation.scss
  style-rtl.css
  style.css
  template-parts/header/site-branding.php
Labels: has patch, needs testing

#538 Update widgets to use sans-serif fonts for all list-style widgets
  sass/blocks/_blocks.scss
  sass/mixins/_mixins-master.scss
  sass/site/secondary/_widgets.scss
  style-editor-customizer.css
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#559 Clean up text alignment & spacing for Cover and Pullquote blocks.
  sass/blocks/_blocks.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#523 Don’t escape translations
  comments.php
  footer.php
  functions.php
  header.php
  image.php
  inc/template-functions.php
  inc/template-tags.php
  search.php
  template-parts/content/content-none.php
  template-parts/content/content-page.php
  template-parts/content/content-single.php
  template-parts/content/content.php
Labels: code quality

#565 Prevent Gutenberg's meta boxes area from overlapping the content
  style-editor.css
  style-editor.scss
Labels: bug

#574 Fix appender specificity issue.
  style-editor.css
  style-editor.scss
Labels: bug

#569 Remove outdated aligncenter styles for the audio block
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug

#581 Improve file block button position
  inc/color-patterns.php
  sass/blocks/_blocks.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#582 Remove negative margins from blockquotes
  sass/elements/_elements.scss
  style-rtl.css
  style.css
Labels: bug

#585 Try: Use non-breaking space override globally
  sass/variables-site/_fonts.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: enhancement

#588 Hide empty links within menu items
  sass/navigation/_menu-main-navigation.scss
  style-rtl.css
  style.css
Labels: bug

#575 Fix so sticky toolbar works again.
  style-editor.css
  style-editor.scss
Labels: bug

#593 Minor: Update header font weight in editor.
  style-editor.css
  style-editor.scss
Labels: bug

#589 Fix priority+ menu in customizer with a full customizer refresh
  js/priority-menu.js
  js/touch-keyboard-navigation.js
  sass/navigation/_menu-main-navigation.scss
  style-rtl.css
  style.css
Labels: bug

#595 Restore README.md line breaks
  README.md
Labels: bug

#597 Try: Removing overflow: hidden from Twitter block
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug

#566 Tidy up our print styles
  print.css
  print.scss
Labels: bug

#606 Prevent the nav-menu ellipses icon from appearing when javascript is disabled
  inc/template-functions.php
  js/priority-menu.js
  sass/navigation/_menu-main-navigation.scss
  style-rtl.css
  style.css
Labels: bug

#607 Submenu: Fix shift-tab navigation and animation
  js/touch-keyboard-navigation.js
  sass/navigation/_menu-main-navigation.scss
  style-rtl.css
  style.css
Labels: bug

#608 Remove our Classic Block gallery shortcode editor styles
  style-editor.css
  style-editor.scss
Labels: bug

#591 Add front end padding to column blocks.
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug

#614 Try: Better position wide and fullwide toolbars.
  style-editor.css
  style-editor.scss
Labels: enhancement

#615 Fix for menu items in the off-canvas menu from overflowing the viewport
  sass/navigation/_menu-main-navigation.scss
  style-rtl.css
  style.css
Labels: bug

#619 Adjust max-width for alignaleft blocks, Clean up line breaks + center alignment for cover blocks
  sass/blocks/_blocks.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#620 Fix minor print styles issues
  print.css
  print.scss
Labels: bug

#623 Move the `&nbsp;` fix to editor-only styles
  sass/variables-site/_fonts.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: code quality

#625 Add post navigation links hovers to color-patterns.php
  inc/color-patterns.php
Labels: bug

#627 Minor: Make search field full-width on small screens
  sass/site/secondary/_widgets.scss
  style-rtl.css
  style.css
Labels: enhancement

#162 Add custom editor font sizes
  functions.php
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: enhancement

#632 Fix reloading issue when an invalid menu-item appears in the menu
  js/priority-menu.js
Labels: bug, high priority

#636 Sync up gallery shortcode math with Gutenberg
  sass/media/_galleries.scss
  style-rtl.css
  style.css
Labels: bug

#637 Simplify selectors for dashes that appear in nested lists
  sass/mixins/_mixins-master.scss
  sass/navigation/_menu-main-navigation.scss
  style-editor.css
  style-rtl.css
  style.css
Labels: code quality

#642 Add additional colors to our editor swatches
  functions.php
  inc/color-patterns.php
  sass/blocks/_blocks.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: enhancement

#640 Minor: Add right padding to the privacy policy link
  sass/site/footer/_site-footer.scss
  style-rtl.css
  style.css
Labels: bug

#639 Fix site logo selective refresh issue
  js/priority-menu.js
Labels: bug

#655 Fix link color within solid-color pullquote blocks
  sass/blocks/_blocks.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: bug

#549 Add theme version to stylesheet
  functions.php
Labels: bug, code quality

#656 Try fixing social icon jumping in Safari
  sass/navigation/_menu-social-navigation.scss
  style-rtl.css
  style.css
Labels: bug

#546 General code and documentation improvements
  archive.php
  classes/class-twentynineteen-svg-icons.php
  functions.php
  header.php
  image.php
  inc/color-patterns.php
  inc/customizer.php
  inc/template-functions.php
  inc/template-tags.php
  index.php
Labels: code quality

#675 Fix critical GitHub security issue
  package-lock.json
  package.json
Labels: bug, high priority, in progress

#670 Include non-breaking space override on the front end
  sass/variables-site/_fonts.scss
  style-editor.css
  style-editor.scss
  style-rtl.css
  style.css
Labels: approved for merge, bug

#674 Add nowrap to the columns block at breakpoints above 600px
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: approved for merge, bug

#683 Fixes #681 — Primary color hue is now properly set
  inc/color-patterns.php
Labels: approved for merge, bug

#684 Add proper frontend styles for center aligned archive and category blocks
  CONTRIBUTORS.md
  sass/blocks/_blocks.scss
  style.css
Labels: approved for merge

#685 Ensure the icons in the classic block toolbar always use dashicons
  style-editor.css
  style-editor.scss
Labels: approved for merge, bug

#686 Remove duplicate rule-line when a separator block is followed by H1/H2 in the editor
  style-editor.css
  style-editor.scss
Labels: approved for merge

#687 Fix gallery caption link color, Recompile CSS
  sass/blocks/_blocks.scss
  style-editor.css
  style-rtl.css
  style.css
Labels: bug

#690 Remove left padding from pullquote blocks
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug

#47 Print skip-link-focus-fix inline instead of enqueueing as blocking script
  functions.php
  js/skip-link-focus-fix.js
Labels: code quality

#217 Fix and improve some strings with placeholders
  classes/class-twentynineteen-walker-comment.php
  inc/template-tags.php
  single.php
  template-parts/post/author-bio.php
Labels: code quality

#237 Added footer translator comment
  classes/class-twentynineteen-walker-comment.php
  comments.php
  template-parts/post/author-bio.php
  template-parts/post/discussion-meta.php
Labels: code quality

#661 Fix PHP Warning: Parameter must be an array or an object that implements Countable
  CONTRIBUTORS.md
  header.php
Labels: bug

#274 Add missing text domain and escaping to comment author text in class-twentynineteen-walker-comment.php
  classes/class-twentynineteen-walker-comment.php
Labels: code quality

#691 Remove hyphens rule for cover image text
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: bug

#693 Add readme.txt
  readme.txt
Labels: task
