Repository WordPress/twentynineteen, pull requests merged in 2019-01, with the labels that each got.

#699 Remove read more arrow underline
  sass/site/primary/_posts-and-pages.scss
  style-rtl.css
  style.css
Labels: added to trac, approved for merge, bug

#702 Try pushing right-aligned images outside of the text column
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: added to trac, approved for merge, bug

#703 Ensure default outline style button has legible text on hover
  sass/blocks/_blocks.scss
  style-rtl.css
  style.css
Labels: added to trac, approved for merge, bug

#710 Updating the Twenty Nineteen description in the .scss file
  README.md
  readme.txt
  style-rtl.css
  style.css
  style.scss
Labels: added to trac, approved for merge, enhancement

#721 #717: Removed redundant link behaviour in touchevents js
  js/touch-keyboard-navigation.js
Labels: added to trac, approved for merge, bug

#730 Clean up opacity and text shadow on submenus when there's a featured image
  sass/navigation/_menu-main-navigation.scss
  sass/site/header/_site-featured-image.scss
  style-rtl.css
  style.css
Labels: added to trac, approved for merge, bug

#735 Fix accessibility in menu markup and JS errors
  inc/template-functions.php
  js/touch-keyboard-navigation.js
  sass/navigation/_menu-main-navigation.scss
  style-rtl.css
  style.css
  template-parts/header/site-branding.php
Labels: added to trac, approved for merge, bug, in progress

#745 Bump version number to match files in Core repo.
  readme.txt
  style.css
  style.scss
Labels: added to trac, approved for merge
